USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
id INT UNSIGNED NOT NULL,
artist VARCHAR (150) NOT NULL,
name VARCHAR (150) NOT NULL,
release_date DATE NOT NULL,
sales DECIMAL(9,2) NOT NULL,
genre VARCHAR (150) NOT NULL,
PRIMARY KEY (id)
);